version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-fusion_app_1
      APP_PORT: 8080

  app:
    image: ghcr.io/0x2e/fusion:0.9.8@sha256:2d98a5bf0cabd6998d07fa26c63f1b742a1c33a4c926f2da1dfd7ee49e88e3e0
    environment:
      - PASSWORD=umbrel
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
