version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-projectsend_app_1
      APP_PORT: 80

  app:
    image: ghcr.io/linuxserver/projectsend:r1720-ls234@sha256:94eb45a6c1754d5dede576dd3e3092ce69b681357b143c57d5ed50102b264206
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOST=mysql
      - DB_NAME=projectsend
      - DB_USER=psuser
      - DB_PASS=pspassword
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
      - ${APP_DATA_DIR}/data/ps_data:/data:rw
    depends_on:
      - db

  db:
    image: mysql:9.3.0@sha256:04768cb63395f56140b4e92cad7c8d9f48dfa181075316e955da75aadca8a7cd
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projectsend
      MYSQL_USER: psuser
      MYSQL_PASSWORD: pspassword
    volumes:
      - ${APP_DATA_DIR}/data/db_data:/var/lib/mysql
