version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-webtor_app_1
      APP_PORT: 8080

  app:
    image: ghcr.io/webtor-io/self-hosted:1.0.4@sha256:5859224c9e4ab55fddec5bd4bd51daf967c7635ae2ad5e19d8c7c91fdfb31322
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data



