version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-expenseowl_web_1
      APP_PORT: 8080

  web:
    image: tanq16/expenseowl:v4.0@sha256:b653c11b46a29d088469513ecc711bcd46b2ba29c9e5afd6e6f89e969fd27a27
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data