version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-radicale_web_1
      APP_PORT: 5232

  web:
    image: tomsquest/docker-radicale:3.5.4.0@sha256:99a1145aafab55f211389a303a553109d06ff2c00f634847a52b8561bd01f172
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data