version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-spooty_web_1
      APP_PORT: 3000

  web:
    image: raiper34/spooty:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/downloads:/spooty/backend/downloads