services:
  app_proxy:
    environment:
      APP_HOST: denny-litechat_app_1
      APP_PORT: 3000

  app:
    image: dimitrigilbert/litechat:0.2.9@sha256:a1e0d8459eaf442f2b37d301914f25e959f4345dc57a8ef9929e6899ceef63c6
    restart: on-failure
    environment:
      - NODE_ENV=production
    depends_on:
      - mcp-bridge
    volumes:
      - ${APP_DATA_DIR}/data/litechat_data:/app/data

  mcp-bridge:
    image: node:20.19.4@sha256:2c071012e93673d595e1399564c4a48a70a5c0a0acd7db8211d5e6f6316b431a
    restart: on-failure
    working_dir: /app
    command: ["node", "bin/mcp-bridge.js", "--host", "0.0.0.0"]
    environment:
      - MCP_BRIDGE_PORT=3001
      - MCP_BRIDGE_HOST=0.0.0.0
      - MCP_BRIDGE_VERBOSE=false
    volumes:
      - ${APP_DATA_DIR}/data/bin/mcp-bridge.js:/app/bin/mcp-bridge.js:rw
