version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-searxng_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/searxng/searxng:2025.7.19-b95a3e9@sha256:8f1196f03960ebae2292ba7b6d3e074c643abded31ad5bb0d0e971e20670156c
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/etc/searxng
