version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-stalwart_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: stalwartlabs/stalwart:v0.12.3@sha256:c24e6a79766b281a0df1d5bd6cb4c7f1d9409737b7911e0075f8b244383de2fa
    restart: on-failure
    tty: true
    stdin_open: true
    ports:
      # "8080:8080"   # Web UI / API
      - "1443:443"     # HTTPS
      - "25:25"       # SMTP
      - "587:587"     # SMTP Submission
      - "465:465"     # SMTPS
      - "143:143"     # IMAP
      - "993:993"     # IMAPS
      - "4190:4190"   # Sieve
      - "110:110"     # POP3
      - "995:995"     # POP3S
    volumes:
      - ${APP_DATA_DIR}/data:/opt/stalwart:rw
