version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-wally_web_1
      APP_PORT: 80

  web:
    image: poliuscorp/wally:1.1@sha256:379e33d295e4b44e971135a5af8955db26fb878b734edbdc02e2381acdc90b83
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/wally/data
    environment:
      DEMO: "true"