version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-glance_app_1
      APP_PORT: 8080

  app:
    image: glanceapp/glance:v0.7.13@sha256:a2371cabe498c5df8ff1e935eee7a383a1a6c9e17def2a18db82810019e5e4ab
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/glance_data/glance.yml:/app/config/glance.yml
      - ${APP_DATA_DIR}/data/assets:/app/assets:rw
      - ${APP_DATA_DIR}/data/timezone:/etc/timezone:ro
      - ${APP_DATA_DIR}/data/localtime:/etc/localtime:ro
