version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-filerise_app_1
      APP_PORT: 80

  app:
    image: error311/filerise-docker:latest@sha256:343b54c7cc1ce53b65b5e83ebbd931d3a8733cb4578fe761a463018ff257f472
    environment:
      TOTAL_UPLOAD_SIZE: "10G"
      SECURE: "false"
      PERSISTENT_TOKENS_KEY: "m7Gd9sVxqPzL4wJ2RbXkNtFhYe3CmHaZ"
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/var/www/uploads
      - ${APP_DATA_DIR}/data/users:/var/www/users
      - ${APP_DATA_DIR}/data/metadata:/var/www/metadata
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s