version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-haptic_web_1
      APP_PORT: 80

  web:
    image: chroxify/haptic-web:v0.1.4@sha256:fd8c09f777c177f9c6fc86acfb81ca9dd8cfa3c64ff379af8be6049ead0d5b97
    restart: on-failure
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
