version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-homarr_web_1
      APP_PORT: 7575

  web:
    image: ghcr.io/homarr-labs/homarr:v1.21.0@sha256:3d97e5e677be2ae0a6451ad5305ea4d9ff011a0fc88b56a25683cf7b666f2788
    restart: on-failure
    environment:
      - SECRET_ENCRYPTION_KEY=390314723a406d9680a370e85604e403655e9d38efff8de6f997ec45eb27c6cd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data:/appdata	