version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-stremio_server_1
      APP_PORT: 8080

  server:
    image: tsaridas/stremio-docker:v1.1.118@sha256:1f7a09b1be001fe4770d2e1c6d8dae0e6c53b59217e3f30038ad3695387b80d9
    ports:
      - 11470:11470 #HTTP
      - 12470:12470 #HTTPS
    environment:
      - NO_CORS=1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/root/.stremio-server
