version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-keycloak_web_1
      APP_PORT: 8080

  db:
    image: postgres:16@sha256:47053cd4ee3f096afc744e53e3280de7b29b3670d2f2196c2acc0c6470923c99
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/keycloakdb:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "keycloakuser"]
      interval: 10s
      timeout: 45s
      retries: 10
    restart: on-failure

  web:
    image: quay.io/keycloak/keycloak:26.2.4@sha256:4a81762677f8911c6266e3dea57a2d78fa17bd63408debbf23afd8cc46fe256e
    user: "1000:1000"
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: keycloakpass
      KC_DB_SCHEMA: public
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: INFO
      KC_HEALTH_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: umbrel
    depends_on:
      - db
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
