version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-pinchflat_web_1
      APP_PORT: 8945

  web:
    image: ghcr.io/kieraneglin/pinchflat:v2025.3.17@sha256:06e20be2ad935f1ee2b527f99d1492086d7b82713739abf016e46632992079ec
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
      - ${APP_DATA_DIR}/data/downloads:/downloads:rw