version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-termix_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/lukegus/termix:release-1.3.0@sha256:c5306bae90a05052f2532984a0d03aae9d46fd7948a67a732af52f71e3a7f4de
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data